import subprocess
from time import sleep
from .test_creator import test_case_creator

SRC_FILE = "user/assignment01p1.cpp"  # The user coded source file
STDOUT_FILE = "temp/user_outputs/"  # The output file generated by the user
TESTDATA_FILE = "tests/a_test01p1.json"  # The testfile for the source files
BUILD_FILE = "build/result"  # The compiled program


def main():

    test_files = test_case_creator(test_file=TESTDATA_FILE)

    # Builds and runs the file
    subprocess.run(["g++", SRC_FILE, "-o", BUILD_FILE])
    sleep(1)
    for counter, file in enumerate(test_files):
        I_file = open(file, "r")
        O_file = open("temp/user_outputs/user_output" + str(counter), "w")

        print("input file contets")
        print(I_file.readlines())

        subprocess.run(["build/result"], stdin=I_file, stdout=O_file)

        O_file.close()

        I_file.close()

    # Checking the result

    # O_file.close()

    # Clean up temp files
    # subprocess.run(["rm", BUILD_FILE, O_file])
